formatting
neovim: add extraLuaPackages to wrapNeovimUnstable

This was available in makeNeovimConfig already but:
- generated wrapper arguments, which we want to avoid because it
  confuses users
- `makeNeovimConfig` relies on neovim-unwrapped in impure manner, which
  for instance caused issues in one of cases where I override
  neovim-unwrapped's luajit with a luajit with custom lua packages.

neovim: compute pure lua deps

list lua dependencies that are not vim plugins and that need to be
exposed via package.path / package.cpath

neovim: compute lua deps at eval time

TODO test by building:

       error: A definition for option `luaDependencies."[definition 1-entry 1]"' is not of type `package'. Definition values:
       - In `<unknown-file>': [ ]

====
with import /home/teto/nixpkgs {};

wrapNeovimUnstable neovim-unwrapped {

  neovimRcContent = "set clipboard=unnamedplus";
  luaRcContent = "print('toto')";

  withPython3 = true;

  plugins = [
    vimPlugins.telescope-nvim
  ];

}
====

neovimUtils: improve error message

Before:

    error: The option `plugins."[definition 1-entry 1]".toto' does not exist. Definition values:
       - In `<unknown-file>': "tata"

After:
    error: The option `plugins."[definition 1-entry 1]".toto' does not exist. Definition values:
    - In `pkgs/applications/editors/neovim/plugin-submodule.nix': "tata"

I've renamed "module.nix" to "plugin-submodule.nix" in case we want to
add a similar module for the top-level wrapper.

mininet: fix eval for nix-index

fixed eval for nix-index