neovim: compute pure lua deps
list lua dependencies that are not vim plugins and that need to be
exposed via package.path / package.cpath

neovim: compute lua deps at eval time

TODO test by building:

       error: A definition for option `luaDependencies."[definition 1-entry 1]"' is not of type `package'. Definition values:
       - In `<unknown-file>': [ ]

====
with import /home/teto/nixpkgs {};

wrapNeovimUnstable neovim-unwrapped {

  neovimRcContent = "set clipboard=unnamedplus";
  luaRcContent = "print('toto')";

  withPython3 = true;

  plugins = [
    vimPlugins.telescope-nvim
  ];

}
====